---
- hosts: all
  become: yes
  vars: 
    - pkg: apache2
    - pkg1: httpd
  tasks:
  - name: install "{{pkg}}" for Ubuntu
    package:
        name: "{{pkg}}"
        state: present
        update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install "{{pkg1}}" for Redhat
    package:
        name: "{{pkg1}}"
        state: present
    when: ansible_distribution == "RedHat"
    notify: service "{{pkg1}}"

  handlers:
  - name: service "{{pkg1}}"
    service:
      name: "{{pkg1}}"
      state: started



